string_a = "{}".format(10)
print(string_a)
print(type(string_a))

print()
format_a = "{}만 원".format(5000)
format_b = "파이썬 열공하여 첫 연봉 {}만 원 만들기".format(5000)
format_c = "{} {} {}".format(3000, 4000, 5000)
format_d = "{} {} {}".format(1, "문자열", True)
print(format_a)
print(format_b)
print(format_c)
print(format_d)

print()
output_a = "{:d}".format(52)
output_b = "{:5d}".format(52)
output_c = "{:10d}".format(52)
output_d = "{:05d}".format(52)
output_e = "{:05d}".format(-52)
output_f = "{:+d}".format(52)
output_g = "{:+d}".format(-52)
output_h = "{: d}".format(52)
output_i = "{: d}".format(-52)
output_j = "{:+5d}".format(52)
output_k = "{:+5d}".format(-52)
output_l = "{:=+5d}".format(52)
output_m = "{:=+5d}".format(-52)
output_n = "{:+05d}".format(52)
output_o = "{:+05d}".format(-52)
print(output_a)
print(output_b)
print(output_c)
print(output_d)
print(output_e)
print(output_f)
print(output_g)
print(output_h)
print(output_i)
print(output_j)
print(output_k)
print(output_l)
print(output_m)
print(output_n)
print(output_o)

print()
put_a = "{:f}".format(52.273)
put_b = "{:15f}".format(52.273)
put_c = "{:+15f}".format(52.273)
put_d = "{:+015f}".format(52.273)
put_e = "{:15.3f}".format(52.273)
put_f = "{:15.2f}".format(52.273)
put_g = "{:15.1f}".format(52.273)
put_h = 52.0
put_i = "{:g}".format(put_h)
print(put_a)
print(put_b)
print(put_c)
print(put_d)
print(put_e)
print(put_f)
print(put_g)
print(put_h)
print(put_i)