print("#하나만 출력합니다.")
print("Hello Python Programming...!")
print()
print("#여러 개를 출력합니다.")
print(10, 20, 30, 40, 50)
print("Hello", "Python", "Programming...!")
print()
print("#아무것도 출력하지 않습니다.")
print("-----------------------")
print()
print()
print()
print("-----------------------")