print("이름\t나이\t지역")
print("abc\t25\tgang")
print("def\t24\tbook")
print("ghi\t30\tgu")
print()
print("문자 선택 연산자에 대해")
print("안녕하세요"[0])
print("안녕하세요"[1])
print("안녕하세요"[2])
print("안녕하세요"[3])
print("안녕하세요"[4])
print()
print("문자 선택 연산자에 대해")
print("안녕하세요"[-1])
print("안녕하세요"[-2])
print("안녕하세요"[-3])
print("안녕하세요"[-4])
print("안녕하세요"[-5])